config:
  url: "https://api.openweathermap.org/data/2.5/weather"
  iconUrl: "http://openweathermap.org/img/wn/"
  appid: "93836445ebca1a81c1081e8b9fa753f0"
  soapNamespace: "http://task.example.com"
  good-status: OK,NOT_ACCEPTABLE
  correlationID: "client1"
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port : 8080